version: '3.10'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: Alisa
      POSTGRES_PASSWORD: 12345
    env_file:
      - .env
    ports:
      - "5432:5432"

  book_recommendations:
    build:
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env