# Generated by Django 4.1.2 on 2023-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.CharField(default="", max_length=200, verbose_name="Авторы"),
            preserve_default=False,
        ),
    ]
