# Generated by Django 4.1.2 on 2023-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_book_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                blank=True, related_name="book", to="mainapp.genre", verbose_name="Жанр"
            ),
        ),
    ]
