# Generated by Django 4.1.2 on 2023-12-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_book_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.CharField(max_length=1000, verbose_name="Авторы"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=1000, verbose_name="Название книги"),
        ),
    ]
